//go:build !templater && !di
// +build !templater,!di

// Code generated by "templater"; DO NOT EDIT.
// source: di.go
package dic

// gen
import (
	"log/slog"
	"strings"

	"github.com/google/wire"
	"github.com/spf13/cobra"
	"github.com/zerops-dev/di/app"
	"github.com/zerops-dev/di/appRunner"
	configurator "github.com/zerops-dev/di/di"
	"github.com/zerops-dev/di/examples/basic/handlers"
	"github.com/zerops-dev/di/examples/basic/services/server"
	"github.com/zerops-dev/di/logger"
)

type Config struct {
	NameLoggerConfig1 logger.Config
	NameServerConfig7 server.Config
}

func NewConfig(prefix string,
	configurator *configurator.Handler,
) *Config {
	c := &Config{
		NameLoggerConfig1: (logger.Config)(logger.NewConfig()),
		NameServerConfig7: (server.Config)(server.NewConfig()),
	}
	configurator.Register(concat(prefix, "log"), &c.NameLoggerConfig1)
	configurator.Register(concat(prefix, "server"), &c.NameServerConfig7)

	return c
}

type NameLoggerConfig1 logger.Config

func GetNameLoggerConfig1(c Config) NameLoggerConfig1 {
	return NameLoggerConfig1(c.NameLoggerConfig1)
}

type NameServerConfig7 server.Config

func GetNameServerConfig7(c Config) NameServerConfig7 {
	return NameServerConfig7(c.NameServerConfig7)
}

type AppConfig struct {
	configurator *configurator.Handler
	config       *Config
}

func NewAppConfig(prefix string, cmd *cobra.Command) *AppConfig {
	configurator := configurator.New(cmd)
	return &AppConfig{
		configurator: configurator,
		config:       NewConfig(prefix, configurator),
	}
}

func (c *AppConfig) Read(app *app.ApplicationSetup, cmd *cobra.Command) error {
	return c.configurator.Read(app, cmd)
}

func (c *AppConfig) Configurator() *configurator.Handler {
	return c.configurator
}

func (c *AppConfig) Register(prefix string, in interface{}) {
	c.configurator.Register(prefix, in)
}

func (c *AppConfig) ConfigCommand(app *app.ApplicationSetup) *cobra.Command {
	return c.configurator.ConfigCommand(app)
}

func (c *AppConfig) Config() Config {
	return *c.config
}

func concat(parts ...string) string {
	var result []string
	for _, part := range parts {
		p := strings.TrimPrefix(part, "<")
		if strings.HasPrefix(part, "<") && len(result) > 0 {
			result[len(result)-1] = p
		} else {
			result = append(result, p)
		}
	}
	return strings.Join(result, ".")
}

type NameSlogLogger0 slog.Logger

func GetNameSlogLogger0(arg0 NameLoggerConfig1,
) *NameSlogLogger0 {

	return (*NameSlogLogger0)(logger.New((logger.Config)(arg0)))

}

type NameAppRunnerHandler2 appRunner.Handler

func GetNameAppRunnerHandler2(arg0 *NameSlogLogger0,
) *NameAppRunnerHandler2 {

	return (*NameAppRunnerHandler2)(appRunner.New((*slog.Logger)(arg0)))

}

type NameAppRunnerRegister3 appRunner.Register

func GetNameAppRunnerRegister3(arg0 *NameAppRunnerHandler2,
) NameAppRunnerRegister3 {

	return (NameAppRunnerRegister3)(appRunner.DiBind((*appRunner.Handler)(arg0)))

}

type NameServerHandler4 server.Handler

func GetNameServerHandler4(arg0 NameServerConfig7,
	arg1 *NameSlogLogger0,
	arg2 NameAppRunnerRegister3,
) (*NameServerHandler4, error) {

	v, err := server.New((server.Config)(arg0),
		(*slog.Logger)(arg1),
		(appRunner.Register)(arg2),
	)
	return (*NameServerHandler4)(v), err

}

type NameHandlersIdentity5 handlers.Identity

func GetNameHandlersIdentity5() *NameHandlersIdentity5 {

	return (*NameHandlersIdentity5)(handlers.NewIdentity())

}

type NameHandlersReverse6 handlers.Reverse

func GetNameHandlersReverse6() *NameHandlersReverse6 {

	return (*NameHandlersReverse6)(handlers.NewReverse())

}

type setter_0 struct{}
type setter_0_Value server.Tools

func getSetter_0_Value(target *NameHandlersIdentity5) (setter_0_Value, error) {

	return (setter_0_Value)((*handlers.Identity)(target)), nil

}

func setSetter_0(source *NameServerHandler4, target setter_0_Value) *setter_0 {

	server.RegisterTools((*server.Handler)(source), target)
	return &setter_0{}

}

type setter_1 struct{}
type setter_1_Value server.Tools

func getSetter_1_Value(target *NameHandlersReverse6) (setter_1_Value, error) {

	return (setter_1_Value)((*handlers.Reverse)(target)), nil

}

func setSetter_1(source *NameServerHandler4, target setter_1_Value) *setter_1 {

	server.RegisterTools((*server.Handler)(source), target)
	return &setter_1{}

}

var DepSet = wire.NewSet(
	app.Set,
	NewApplication, getSetter_0_Value, setSetter_0,
	getSetter_1_Value, setSetter_1,
	GetNameSlogLogger0,
	GetNameAppRunnerHandler2,
	GetNameAppRunnerRegister3,
	GetNameServerHandler4,
	GetNameHandlersIdentity5,
	GetNameHandlersReverse6,

	GetNameLoggerConfig1,
	GetNameServerConfig7,
)

func NewApplication(
	systemApp *app.ApplicationSetup, _ *setter_0,
	_ *setter_1,
	logger00 *NameSlogLogger0,
	runner21 *NameAppRunnerHandler2,
	_ NameAppRunnerRegister3,
	_ *NameServerHandler4,
	_ *NameHandlersIdentity5,
	_ *NameHandlersReverse6,
) *App {
	return &App{
		app:    systemApp,
		logger: (*slog.Logger)(logger00),
		runner: (*appRunner.Handler)(runner21),
	}
}

type App struct {
	app    *app.ApplicationSetup
	logger *slog.Logger
	runner *appRunner.Handler
}

func (h *App) GetLogger() *slog.Logger {
	return h.logger
}
func (h *App) GetRunner() *appRunner.Handler {
	return h.runner
}
func (h *App) Run() error {
	return h.runner.RunWithSigTerm(h.app.Context, h.app.Cancel)
}

func CreateCommand(app *app.ApplicationSetup) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "run",
		Short: "run command",
		Long:  "",
	}

	cfg := NewAppConfig("example-app", cmd)

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if err := cfg.Read(app, cmd); err != nil {
			return err
		}

		application, err := CreateApp(app, cfg.Config())
		if err != nil {
			panic(err)
		}
		return application.Run()
	}
	cmd.AddCommand(cfg.ConfigCommand(app))

	return cmd
}
